//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yemnak.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerTb
    {
        public int PartnerID { get; set; }
        public Nullable<int> CrdHolderID { get; set; }
        public string PartnerName { get; set; }
        public string PartnerPhone { get; set; }
        public string PartnerEmail { get; set; }
        public string PartnerAddress { get; set; }
        public string PartnerCivilId { get; set; }
        public Nullable<System.DateTime> PartnerBOD { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
    }
}
