//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yemnak.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersTb
    {
        public int UserId { get; set; }
        public string userName { get; set; }
        public string userPassword { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
    }
}
