//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yemnak.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YemnakDBEntities : DbContext
    {
        public YemnakDBEntities()
            : base("name=YemnakDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChildrenTb> ChildrenTbs { get; set; }
        public virtual DbSet<ClassicTb> ClassicTbs { get; set; }
        public virtual DbSet<OrderTb> OrderTbs { get; set; }
        public virtual DbSet<PartnerTb> PartnerTbs { get; set; }
        public virtual DbSet<PlatinumTb> PlatinumTbs { get; set; }
        public virtual DbSet<PremierTb> PremierTbs { get; set; }
        public virtual DbSet<PrestigeTb> PrestigeTbs { get; set; }
        public virtual DbSet<UsersTb> UsersTbs { get; set; }
    }
}
