//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace yemnak.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SiteResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("yemnak.App_GlobalResources.SiteResources", typeof(SiteResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From the goals that the Public Services Company were built for, which is to help citizens from all over the state private and public institutions to facilitate procedures, and from the company&apos;s vision which is to present superior services, Yemnak Concierge was built, since 2003. Yemnak is a service given for our elite clients, individuals and companies, to help out with your needs and to help you with your daily tasks in privacy. Yemnak team will satisfy your needs where they will take you to a luxurious t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string About_Yemnak_Para {
            get {
                return ResourceManager.GetString("About_Yemnak_Para", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bringing Services to you since 2003.
        /// </summary>
        public static string About_Yemnak_Subtitle {
            get {
                return ResourceManager.GetString("About_Yemnak_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Yemnak.
        /// </summary>
        public static string About_Yemnak_Title {
            get {
                return ResourceManager.GetString("About_Yemnak_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string AboutUs_Detail {
            get {
                return ResourceManager.GetString("AboutUs_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concierge Individuals and Company.
        /// </summary>
        public static string Card_Title_First {
            get {
                return ResourceManager.GetString("Card_Title_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yemnak&apos;s team are ready to serve you 24/7 to facilitate your daily tasks, to create a unique and luxurious lifestyle to our clients. These services provided to our clients through annual contracts with different companies for their clients, or by individual&apos;s membership contracts. We designed our services to suit your needs and wants which will help you through your day..
        /// </summary>
        public static string Card_Title_First_Detail {
            get {
                return ResourceManager.GetString("Card_Title_First_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completing transactions, which does not require a personal attendance..
        /// </summary>
        public static string Card_Title_First_LIstitem_1 {
            get {
                return ResourceManager.GetString("Card_Title_First_LIstitem_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finishing transactions through different embassies and Ministry of Foreign Affairs.
        /// </summary>
        public static string Card_Title_First_LIstitem_10 {
            get {
                return ResourceManager.GetString("Card_Title_First_LIstitem_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transportations from / to airports.
        /// </summary>
        public static string Card_Title_First_LIstitem_11 {
            get {
                return ResourceManager.GetString("Card_Title_First_LIstitem_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking hotels, tickets, restaurants, etc....
        /// </summary>
        public static string Card_Title_First_LIstitem_12 {
            get {
                return ResourceManager.GetString("Card_Title_First_LIstitem_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On road services.
        /// </summary>
        public static string Card_Title_First_LIstitem_13 {
            get {
                return ResourceManager.GetString("Card_Title_First_LIstitem_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paying fees (schools, bills, electricity, traffic violations, etc...).
        /// </summary>
        public static string Card_Title_First_LIstitem_14 {
            get {
                return ResourceManager.GetString("Card_Title_First_LIstitem_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery services (flowers, gifts, invitations, etc...).
        /// </summary>
        public static string Card_Title_First_LIstitem_15 {
            get {
                return ResourceManager.GetString("Card_Title_First_LIstitem_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All kind of services that needed by our clients that suits our policies and Shariaa&apos;.
        /// </summary>
        public static string Card_Title_First_LIstitem_16 {
            get {
                return ResourceManager.GetString("Card_Title_First_LIstitem_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Establishing / renew / cancel an immigrants visa..
        /// </summary>
        public static string Card_Title_First_LIstitem_2 {
            get {
                return ResourceManager.GetString("Card_Title_First_LIstitem_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comprehensive medical examination.
        /// </summary>
        public static string Card_Title_First_LIstitem_3 {
            get {
                return ResourceManager.GetString("Card_Title_First_LIstitem_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transporting data from passport to another.
        /// </summary>
        public static string Card_Title_First_LIstitem_4 {
            get {
                return ResourceManager.GetString("Card_Title_First_LIstitem_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Driving license renewal.
        /// </summary>
        public static string Card_Title_First_LIstitem_5 {
            get {
                return ResourceManager.GetString("Card_Title_First_LIstitem_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical inspection for cars and car registration renewal..
        /// </summary>
        public static string Card_Title_First_LIstitem_6 {
            get {
                return ResourceManager.GetString("Card_Title_First_LIstitem_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replacing old car plates with new one.
        /// </summary>
        public static string Card_Title_First_LIstitem_7 {
            get {
                return ResourceManager.GetString("Card_Title_First_LIstitem_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa for tourism or for students.
        /// </summary>
        public static string Card_Title_First_LIstitem_8 {
            get {
                return ResourceManager.GetString("Card_Title_First_LIstitem_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civil ID renewal.
        /// </summary>
        public static string Card_Title_First_LIstitem_9 {
            get {
                return ResourceManager.GetString("Card_Title_First_LIstitem_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Center.
        /// </summary>
        public static string Card_Title_Second {
            get {
                return ResourceManager.GetString("Card_Title_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To keep up with our client&apos;s needs we provided a call center to help for establishing high standards for our services. We provide this a Call Center Services to companies with employees who are ready to answer calls for them. In addition, there is a call center in our company with the latest technology to serve different companies and governments..
        /// </summary>
        public static string Card_Title_Second_Detail {
            get {
                return ResourceManager.GetString("Card_Title_Second_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Call Center also provide different services:.
        /// </summary>
        public static string Card_Title_Second_Detail2 {
            get {
                return ResourceManager.GetString("Card_Title_Second_Detail2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming and outgoing calls services.
        /// </summary>
        public static string Card_Title_Second_LIstitem_1 {
            get {
                return ResourceManager.GetString("Card_Title_Second_LIstitem_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data entering services.
        /// </summary>
        public static string Card_Title_Second_LIstitem_10 {
            get {
                return ResourceManager.GetString("Card_Title_Second_LIstitem_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing campaigns.
        /// </summary>
        public static string Card_Title_Second_LIstitem_2 {
            get {
                return ResourceManager.GetString("Card_Title_Second_LIstitem_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey campaigns.
        /// </summary>
        public static string Card_Title_Second_LIstitem_3 {
            get {
                return ResourceManager.GetString("Card_Title_Second_LIstitem_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guidance and awareness campaigns.
        /// </summary>
        public static string Card_Title_Second_LIstitem_4 {
            get {
                return ResourceManager.GetString("Card_Title_Second_LIstitem_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text messaging services.
        /// </summary>
        public static string Card_Title_Second_LIstitem_5 {
            get {
                return ResourceManager.GetString("Card_Title_Second_LIstitem_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email messaging services.
        /// </summary>
        public static string Card_Title_Second_LIstitem_6 {
            get {
                return ResourceManager.GetString("Card_Title_Second_LIstitem_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertising services.
        /// </summary>
        public static string Card_Title_Second_LIstitem_7 {
            get {
                return ResourceManager.GetString("Card_Title_Second_LIstitem_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fellow-up services.
        /// </summary>
        public static string Card_Title_Second_LIstitem_8 {
            get {
                return ResourceManager.GetString("Card_Title_Second_LIstitem_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consulting and training services.
        /// </summary>
        public static string Card_Title_Second_LIstitem_9 {
            get {
                return ResourceManager.GetString("Card_Title_Second_LIstitem_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string Clients {
            get {
                return ResourceManager.GetString("Clients", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here for Google Map.
        /// </summary>
        public static string ContactUs_googlelink {
            get {
                return ResourceManager.GetString("ContactUs_googlelink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get In Touch With Us.
        /// </summary>
        public static string ContactUS_Title {
            get {
                return ResourceManager.GetString("ContactUS_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright © 2017 All rights reserved Public Service Company Kuwait.
        /// </summary>
        public static string Copyright {
            get {
                return ResourceManager.GetString("Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YEMNAK is one of the services provided by Public Services Company. The service has been launched since 2003 and one of our first and current main clients are the General Secretariat of the Council of Ministers..
        /// </summary>
        public static string Footer_Aboutus {
            get {
                return ResourceManager.GetString("Footer_Aboutus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DIVERSIFIED SERVICES.
        /// </summary>
        public static string Header_heading {
            get {
                return ResourceManager.GetString("Header_heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNVARYING QUALITY.
        /// </summary>
        public static string Header_Heading_2 {
            get {
                return ResourceManager.GetString("Header_Heading_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yemnak&apos;s concierge service which provides customers with all the services they require, such as completing government transactions in Kuwait also airport delivery which Yemnak achieves the highest level of luxury for VIP&apos;s..
        /// </summary>
        public static string Home_Page_Header_Para {
            get {
                return ResourceManager.GetString("Home_Page_Header_Para", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn More.
        /// </summary>
        public static string Learn_More_Btn {
            get {
                return ResourceManager.GetString("Learn_More_Btn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Media.
        /// </summary>
        public static string Media {
            get {
                return ResourceManager.GetString("Media", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wide Range of Services Tailored Just For You.
        /// </summary>
        public static string MembershipCard_subtitle {
            get {
                return ResourceManager.GetString("MembershipCard_subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership Cards.
        /// </summary>
        public static string MembershipCard_Title {
            get {
                return ResourceManager.GetString("MembershipCard_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership Request.
        /// </summary>
        public static string MembershipRequest {
            get {
                return ResourceManager.GetString("MembershipRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide all the possibilities that we can offer in Concierge Services, to provide the best services to our clients..
        /// </summary>
        public static string Our_Mission_Detail {
            get {
                return ResourceManager.GetString("Our_Mission_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our Mission.
        /// </summary>
        public static string Our_Mission_Title {
            get {
                return ResourceManager.GetString("Our_Mission_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Yemnak we believe that you deserve a Luxury Lifestyle, so our vision is to take the lead in Concierge Services worldwide..
        /// </summary>
        public static string Our_Vision_Detail {
            get {
                return ResourceManager.GetString("Our_Vision_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OUR VISION.
        /// </summary>
        public static string Our_Vision_Title {
            get {
                return ResourceManager.GetString("Our_Vision_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Services {
            get {
                return ResourceManager.GetString("Services", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to adapted to your needs.
        /// </summary>
        public static string Services_Subtitle {
            get {
                return ResourceManager.GetString("Services_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unmatched Services.
        /// </summary>
        public static string Services_Title {
            get {
                return ResourceManager.GetString("Services_Title", resourceCulture);
            }
        }
    }
}
